### ISSUE TITLE
On older systemd, systemd-networkd unsets zerotier routes/addresses

### ISSUE THREAD

**Issue by laduke** [zerotier/zerotier-systemd-manager#17]
This took a minute to figure out. I'm on an embedded thing that is stuck on an older systemd for now. 

Restarting sytsemd-networkd would unconfigure my zerotier addresses and routes. 

I found this in the journal

```
Aug 17 09:00:57 nanopi-r2s systemd-networkd[14938]: /etc/systemd/network/99-ztqu3i566v.network:9: Unknown lvalue 'KeepConfiguration' in section 'Network', ignoring
```

```
systemctl --version
systemd 241 (241)
```

Then I found out there used to be an option called:
[DHCP]
CriticalConnection=true

so I created a file called 100-zt.network
```
[Match]
Name=zt*

[DHCP]
CriticalConnection=true
```

this seems to be playing nice with zerotier-systemd-manager. 

Not sure if anything needs to be done in this repo. Just wanted to leave some breadcrumbs. 

https://github.com/systemd/systemd/blob/f6e40037a0c6f027fd30e141092dd4982cc56050/NEWS#L3181

**Comment by laduke** [comment]
Wait sorry. adding that CriticalConnection thing seems to make the DNS settings not apply.

**Comment by laduke** [comment]
OK this drop-in thing works, but not sure how to override all zerotier networks in one file yet. 
```
cat 99-ztqu3i566v.network.d/zt.conf
[DHCP]
CriticalConnection=true
```

**Comment by laduke** [comment]
Also, `networkctl reload` doesn't exist on older systemd. (see #15)

systemd 241 is from 2019. 

cat /etc/debian_version
10.9

I don't know if we care about these things or not. I don't personally actually need zerotier dns that badly on this device.

**Comment by erikh** [comment]
hey I just saw this sorry. Is recent debian still this way?

**Comment by laduke** [comment]
hey! I have almost no memory of writing this stuff. 

> Is recent debian still this way? 

I don't think so. Seems fine.

**Comment by shbatm** [comment]
Still having issues on Debian Buster using systemd 241

**Comment by erikh** [comment]
Ok, I don't have a good response for this other than "upgrade systemd-networkd" as it seems to be the problem.

Closing this ticket, but it's good to know this problem exists.
