### ISSUE TITLE
This doesn't appear to work on Ubuntu 22.04

### ISSUE THREAD

**Issue by micush** [zerotier/zerotier-systemd-manager#20]
This doesn't appear to work on Ubuntu 22.04. After installation and connection to my zerotier network, I get this:

# resolvectl
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp0s3)
Current Scopes: DNS
     Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
   DNS Servers: 192.168.122.1

Link 4 (zts4upxgyt)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

# zerotier-cli -j listnetworks
[
 {
  "allowDNS": true,
...
  "dns": {
   "domain": "abc.local",
   "servers": [
    "192.168.55.5",
    "192.168.55.15"
   ]
  },

**Comment by itsmexxie** [comment]
I'm also having trouble setting this up on Ubuntu 22.04. systemd-resolved seems to know about the configured search domains given its output, however it seems to have no idea about the DNS server itself, or even when it should contact some other DNS server other than my default one.
EDIT: Seems that I incorrectly understood the systemctl status output, that's there by default, so it probably doesn't know anything at all.

![image](https://user-images.githubusercontent.com/49583148/220291984-8ac4e54b-fc00-45ae-87fa-7f8c2e6f875f.png)
![image](https://user-images.githubusercontent.com/49583148/220292177-75553665-2fc6-4d20-ae7e-6e721e9f1f89.png)

**Comment by laduke** [comment]
sorry we missed this. Are there any complaints about the unit file in `dmesg` or `journalctl`? 

I haven't been on ubuntu 22.04 recently so don't remember more precise logs. 

`networkctl reload; networkctl reconfigure <zt-interface>` might kick it to try again so you can see easier.

**Comment by itsmexxie** [comment]
Sorry for the late response,
to answer your question, no, there doesn't seem to be any complaints about the unit file. However, it seems that Ubuntu 22.04 doesn't use `systemd-networkd` to manage network connections, it uses NetworkManager, and, as far as my knowledge goes, thsi uses network files in `/etc/systemd/network` that are managed by `systemd-networkd`, so maybe the problem lies there?

**Comment by laduke** [comment]
yeah this is for systemd-networkd. maybe you can tell network manager to ignore your zerotier interfaces. it's a bummer that there are 100 different ways to manage networks and dns on linux.

**Comment by glimberg** [comment]
`systemd-networkd` can coexist with Network Manager.  I run Ubuntu 22.04 for my daily driver, and this works just fine.  Unfortunately I can't recreate what you're seeing:

```
Link 5 (ztijaz7tkl)
    Current Scopes: DNS
         Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.192.73
       DNS Servers: 192.168.192.73
        DNS Domain: ~192.168.192.in-addr.arpa ~dnstest.zt
```

**Comment by erikh** [comment]
I'll try to look at this next week, I will have an ubuntu machine to test with.

------- Original Message -------

**Comment by erikh** [comment]
I was unable to reproduce this issue on ubuntu server, at least.

**Comment by erikh** [comment]
fwiw `lsb_release -a` output:

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Comment by aevela** [comment]
I'm having issues on well on Xubuntu 22 in combination with zerons.

When using dig the IP address of bobby.myztnework.com is correctly returned by the zerons server:
```
>> dig +short @10.147.20.10 bobby.myztnework.com
 10.147.20.202
```

However, when performing a ping
```>> ping ping bobby.myztnetwork.com

ping: bobby.myztnetwork.com: Name or service not known
```
-----------------------------
Edit.  Okay, got things working.  laduke's comment guided the fix on my computer.
```
>>  sudo networkctl reload
WARNING: systemd-networkd is not running, output will be incomplete.
```

So, looks like systemd-networkd isn't working.  Checking system status to confirm:
```
sudo  systemctl status systemd-networkd
○ systemd-networkd.service - Network Configuration
     Loaded: loaded (/lib/systemd/system/systemd-networkd.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
TriggeredBy: ○ systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
```

Let's try starting it to see what happens:
```
sudo systemctl start systemd-networkd
sudo systemctl enable systemd-networkd
```

Now trying laduke's comments again
```
sudo networkctl reload
sudo networkctl reconfigure ztkseqpe62
```
No issues reported this time.  Onto ping test:
```>> ping ping bobby.myztnetwork.com
PING bobby.myztnetwork.com (10.147.20.202) 56(84) bytes of data.
64 bytes from bobby.myztnetwork.com (10.147.20.202): icmp_seq=1 ttl=64 time=82.4 ms
64 bytes from bobby.myztnetwork.com (10.147.20.202): icmp_seq=2 ttl=64 time=31.8 ms
```

Problem solved! (at least on my end)

**Comment by erikh** [comment]
this is probably because:

- the timer isn't running
- systemd-networkd isn't running
- systemd-resolved isn't running

The package should init all of these, and I'm not sure why it didn't for you, but these are the things I'd check first.

------- Original Message -------

**Comment by laduke** [comment]
It sounds like the issue was systemd-networkd wasn't running. Please comment if that's not it and you can provide steps to reproduce.
