### ISSUE TITLE
Package does not enable (or even start) `systemd-networkd`

### ISSUE THREAD

**Issue by mhanuszh** [zerotier/zerotier-systemd-manager#26]
I'm on Fedora 38, and after installing the `zerotier-systemd-manager_0.4.0_linux_amd64.rpm` the zerotier name resolution does not work without manually restarting `systemd-networkd`. This is also the case after each reboot.

**Comment by mhanuszh** [comment]
`systemd-networkd` was not enabled, just like the others (#20) pointed out.

**Comment by laduke** [comment]
I don't think we can just turn on systemd-networkd; maybe we can put a reminder in the instructions.

**Comment by svanegmond** [comment]
If there's an apt dependency you can reaonably enable the package you depend on. I couldn't figure out why my Debian 12 install didn't work, and I hadn't heard of systemd-networkd until today.
