### ISSUE TITLE
Doesn't work if  /etc/hosts isn't properly populated

### ISSUE THREAD

**Issue by ilyasdc** [zerotier/zerotier-systemd-manager#27]
Hello,

I spent much more time I care to admit for understanding why your program wasn't working.
I got such elusive (at least for me) errors on archlinux:
```bash
Mar 18 22:04:11 envyx360 systemd[1]: Starting Update zerotier per-interface DNS settings...
Mar 18 22:04:11 envyx360 zerotier-systemd-manager[715152]: Get "http://localhost:9993/network": dial tcp: lookup localhost on 192.168.1.1:53: no such host
Mar 18 22:04:11 envyx360 systemd[1]: zerotier-systemd-manager.service: Main process exited, code=exited, status=1/FAILURE
Mar 18 22:04:11 envyx360 systemd[1]: zerotier-systemd-manager.service: Failed with result 'exit-code'.
Mar 18 22:04:11 envyx360 systemd[1]: Failed to start Update zerotier per-interface DNS settings.
```

In the end the archlinux wiki (as always) pointed me in the right direction (https://wiki.archlinux.org/title/Network_configuration#localhost_is_resolved_over_the_network) that I had to populate /etc/hosts

> [nss-myhostname(8)](https://man.archlinux.org/man/nss-myhostname.8) (an [NSS](https://wiki.archlinux.org/title/Name_Service_Switch) module provided by [systemd](https://wiki.archlinux.org/title/Systemd) and enabled by default in /etc/nsswitch.conf) provides localhost and the local hostname resolution to an IP address. **Some software may, however, still instead read /etc/hosts directly**; see [[4]](https://lists.debian.org/debian-devel/2013/07/msg00809.html) [[5]](https://bugzilla.mozilla.org/show_bug.cgi?id=87717#c55) for examples.

Note that it is the first time I need to fix this ( I could access localhost from within a browser without problem).

**Comment by laduke** [comment]
Sorry about that. Looks like some battle between go, glibc, arch, etc...

https://bugs.archlinux.org/task/56684

I wouldn't be surprised if all `go` programs that connect to `localhost` are affected. Please add something to the README if you think it would help.

**Comment by ilyasdc** [comment]
Done, see #28

**Comment by laduke** [comment]
thanks!
