### ISSUE TITLE
Rocky linux 8.10

### ISSUE THREAD

**Issue by CrisCard0so** [zerotier/zerotier-systemd-manager#29]
Error in zerotier-systemd-manager.service

`[root@pinocho ~]# systemctl status zerotier-systemd-manager.service 
● zerotier-systemd-manager.service - Update zerotier per-interface DNS settings
   Loaded: loaded (/usr/lib/systemd/system/zerotier-systemd-manager.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2024-08-10 14:04:49 CST; 40s ago
  Process: 33826 ExecStart=/usr/bin/zerotier-systemd-manager (code=exited, status=1/FAILURE)
 Main PID: 33826 (code=exited, status=1/FAILURE)

Aug 10 14:04:49 pinocho systemd[1]: Starting Update zerotier per-interface DNS settings...
Aug 10 14:04:49 pinocho zerotier-systemd-manager[33826]: open /etc/systemd/network: no such file or directory
Aug 10 14:04:49 pinocho systemd[1]: zerotier-systemd-manager.service: Main process exited, code=exited, status=1/FAILURE
Aug 10 14:04:49 pinocho systemd[1]: zerotier-systemd-manager.service: Failed with result 'exit-code'.
Aug 10 14:04:49 pinocho systemd[1]: Failed to start Update zerotier per-interface DNS settings.`

**Comment by CrisCard0so** [comment]
Maybe it's because the root config of these files are under>


In Rocky Linux 8, the storage location for network configuration was in /etc/sysconfig/Network-Scripts/. With Rocky Linux 9, the new default storage location for the key files is in /etc/NetworkManager/system-connections.

**Comment by devvick** [comment]
Neither `/etc/sysconfig/Network-Scripts/` nor `/etc/NetworkManager/system-connections` are related to **systemd-networkd**, which this app is designed to maintain. They might be using systemd-networkd as "backend", but it looks like your system doesn't use it, as evidenced by this line:
```
Aug 10 14:04:49 pinocho zerotier-systemd-manager[33826]: open /etc/systemd/network: no such file or directory
```

**Comment by CrisCard0so** [comment]
In that case  what other options I do have ?????

**Comment by CrisCard0so** [comment]
In the mean time I crated a registry A in the public DNS

**Comment by laduke** [comment]
Sorry. There are 100 ways to do networking in linux and it's confusing. 
Using public dns was my preferred way, but lots of people disagree and get mad at the suggestion. 

I'm not familiar with what rocky uses for dns or if it can do per domain dns servers. If it does, you might manually set it up to use your dns server for your zerotier network's domain. 

You might be able to just start systemd-resolved and retry systemd-manager, but it will probably conflict in some weird hard to understand way. Haven't tried!

https://wiki.archlinux.org/title/Systemd-resolved#Setting_DNS_servers

**Comment by CrisCard0so** [comment]
Yeah, but I was trying to use zero tier ... I know how to create my own ... so seems like this Zerotier is not fully compatible with Rocky. 
Thanks again.

**Comment by devvick** [comment]
@cristiancardosodexcom This package is just a helper for configuring DNS settings with systemd-networkd and systemd-resolved - not NetworkManager. Your distro doesn't matter as much as which networking solution you are using. I'm not familliar with Rocky, but for example in Archlinux you can utilize different solutions according to your needs: https://wiki.archlinux.org/title/Network_configuration#Network_managers
