### ISSUE TITLE
Dependencies override for zerotier-one.service may be unnecessary

### ISSUE THREAD

**Issue by devvick** [zerotier/zerotier-systemd-manager#9]
https://github.com/zerotier/zerotier-systemd-manager/blob/bceddd8896bb4d37125de17935253b1fc7252cdc/contrib/zerotier-one.service#L3-L4

The original .service file lists `network-online.target` as a dependency in both After= and Wants= directives, which, if one's using systemd-networkd (assumed every user of this particular app), already satisfies the dependency on systemd-networkd:
```
systemd-analyze critical-chain zerotier-one.service

zerotier-one.service @13min 6.079s
└─network-online.target @7.650s
  └─systemd-networkd-wait-online.service @735ms +6.915s
    └─systemd-networkd.service @694ms +39ms
```
Overwriting that may make zerotier-one start before network is up which is bound to cause problems, like:
https://github.com/zerotier/ZeroTierOne/issues/1259

As per https://wiki.archlinux.org/title/Systemd#Running_services_after_the_network_is_up
> If using systemd-networkd, systemd-networkd-wait-online.service is enabled together with systemd-networkd.service. Check if this is the case with `systemctl is-enabled systemd-networkd-wait-online.service`. If it is not enabled, then reenable systemd-networkd.service.

**Comment by erikh** [comment]
ok you are correct :) thanks for the ticket. Patch coming RSN.
